# Site settings
title: PDF4J Projects News
email: srbala@gmail.com
description: "PDF4J, Java PDF tools."
url: "https://pdf4j.github.io"
baseurl: "/news"

# Build settings
markdown: kramdown
#permalink: prettay

paginate: 8

kramdown:
  input: GFM
  hard_wrap: false

logo: /favicon.png

gems:
  - jekyll-paginate
  - jemoji
#  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
